name: Deploy Frontend and Backend to Azure App Services

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Backend to Azure Web App (Linux)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_BACKEND_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
        package: .

  deploy-frontend:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies and build
      run: |
        cd frontend
        npm install
        npm run build

    - name: Deploy Frontend to Azure Web App (Linux)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_FRONTEND_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
        package: './frontend/build'
