name: CI/CD Pipeline for React and Python APIs

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  # Deploy React App to Linux App Service
  deploy-frontend:
    runs-on: self-hosted  # Specify your self-hosted runner
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify the Node.js version

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Build the React app
      working-directory: frontend
      run: npm run build

    - name: Deploy to Azure Web App (Linux)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.REACT_APP_SERVICE_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.REACT_APP_PUBLISH_PROFILE }}
        package: frontend/build

  # Deploy Python API to Windows App Service
  deploy-backend:
    runs-on: self-hosted  # Specify your self-hosted runner
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App (Windows)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.PYTHON_APP_SERVICE_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.PYTHON_APP_PUBLISH_PROFILE }}
